spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reactappdb
    username: postgres
    password: ld2erw71904
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
